import type { BankQuestion } from '../types';

export const sortingQuestions: BankQuestion[] = [
  // ─── Multiple Choice (5) ──────────────────────────────────────────────────
  {
    id: 'mc-sorting-001',
    type: 'multiple_choice',
    topic: 'Sorting',
    subtopic: 'sorted',
    difficulty: 'beginner',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    body: 'What does sorted([3, 1, 2]) return?',
    options: ['[3, 1, 2]', '[1, 2, 3]', 'None', '[2, 1, 3]'],
    correct_index: 1,
    explanation: 'sorted() returns a new list with elements in ascending order by default.',
  },
  {
    id: 'mc-sorting-002',
    type: 'multiple_choice',
    topic: 'Sorting',
    subtopic: 'sorted',
    difficulty: 'beginner',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    body: 'What is the difference between .sort() and sorted()?',
    options: [
      'They are identical',
      '.sort() modifies the list in place; sorted() returns a new list',
      'sorted() modifies the list in place; .sort() returns a new list',
      '.sort() works on any iterable; sorted() only works on lists',
    ],
    correct_index: 1,
    explanation: '.sort() is a list method that sorts in place (returns None). sorted() is a built-in function that returns a new sorted list.',
  },
  {
    id: 'mc-sorting-003',
    type: 'multiple_choice',
    topic: 'Sorting',
    subtopic: 'key',
    difficulty: 'intermediate',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    body: 'How do you sort a list of strings by their length?',
    options: [
      'sorted(lst, length=True)',
      'sorted(lst, key=len)',
      'sorted(lst, by="length")',
      'lst.sort(len)',
    ],
    correct_index: 1,
    explanation: 'The key parameter accepts a function that transforms each element for comparison. key=len sorts by string length.',
  },
  {
    id: 'mc-sorting-004',
    type: 'multiple_choice',
    topic: 'Sorting',
    subtopic: 'lambda',
    difficulty: 'intermediate',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    body: 'What does sorted([(1,"b"), (2,"a")], key=lambda x: x[1]) return?',
    options: [
      '[(1, "b"), (2, "a")]',
      '[(2, "a"), (1, "b")]',
      '[("a", 2), ("b", 1)]',
      'Error',
    ],
    correct_index: 1,
    explanation: 'The lambda extracts element [1] (the string) for comparison. "a" < "b", so (2,"a") comes first.',
  },
  {
    id: 'mc-sorting-005',
    type: 'multiple_choice',
    topic: 'Sorting',
    subtopic: 'comprehensions',
    difficulty: 'advanced',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    body: 'What does [x**2 for x in range(5) if x % 2 == 0] produce?',
    options: ['[0, 4, 16]', '[1, 9, 25]', '[0, 1, 4, 9, 16]', '[4, 16]'],
    correct_index: 0,
    explanation: 'range(5) gives 0-4. Even numbers: 0, 2, 4. Their squares: 0, 4, 16.',
  },

  // ─── Open Answer (3) ──────────────────────────────────────────────────────
  {
    id: 'oa-sorting-001',
    type: 'open_answer',
    topic: 'Sorting',
    subtopic: 'sorted',
    difficulty: 'beginner',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    body: 'How do you sort a list in descending (reverse) order using sorted()?',
    acceptable_answers: ['sorted(lst, reverse=True)', 'sorted(list, reverse=True)', 'reverse=True'],
    explanation: 'Pass reverse=True to sorted() to sort in descending order.',
    grading_hint: 'Accept any answer mentioning reverse=True',
  },
  {
    id: 'oa-sorting-002',
    type: 'open_answer',
    topic: 'Sorting',
    subtopic: 'lambda',
    difficulty: 'intermediate',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    body: 'Write a lambda function that takes a string and returns its length.',
    acceptable_answers: ['lambda s: len(s)', 'lambda x: len(x)', 'lambda s:len(s)', 'lambda x:len(x)'],
    explanation: 'lambda s: len(s) is an anonymous function that returns the length of its argument.',
    grading_hint: 'Accept any lambda with len() call on the parameter',
  },
  {
    id: 'oa-sorting-003',
    type: 'open_answer',
    topic: 'Sorting',
    subtopic: 'comprehensions',
    difficulty: 'intermediate',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    body: 'What is the output of [x * 2 for x in [1, 2, 3]]?',
    acceptable_answers: ['[2, 4, 6]'],
    explanation: 'The list comprehension doubles each element: 1*2=2, 2*2=4, 3*2=6.',
  },

  // ─── Coding (3) ───────────────────────────────────────────────────────────
  {
    id: 'code-sorting-001',
    type: 'coding',
    topic: 'Sorting',
    subtopic: 'key',
    difficulty: 'intermediate',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    title: 'Sort by Last Character',
    description: 'Write a function sort_by_last(words) that returns a list of words sorted by their last character.',
    exercise_type: 'write_from_scratch',
    starter_code: `def sort_by_last(words):
    # your code here
    pass`,
    solution_code: `def sort_by_last(words):
    return sorted(words, key=lambda w: w[-1])`,
    hints: ['Use sorted() with a key function.', 'Access the last character with [-1].', 'A lambda is a concise way to define the key function.'],
    test_cases: [
      { id: 1, description: 'Sort by last char', setup_code: '', call_code: 'print(sort_by_last(["abc", "xyz", "bba"]))', expected_output: "['bba', 'abc', 'xyz']" },
      { id: 2, description: 'Already sorted', setup_code: '', call_code: 'print(sort_by_last(["a", "b", "c"]))', expected_output: "['a', 'b', 'c']" },
    ],
  },
  {
    id: 'code-sorting-002',
    type: 'coding',
    topic: 'Sorting',
    subtopic: 'comprehensions',
    difficulty: 'intermediate',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    title: 'Even Squares',
    description: 'Fill in the blank to create a list comprehension that produces squares of even numbers from 1 to 10.',
    exercise_type: 'fill_blank',
    starter_code: `result = [____ for x in range(1, 11) if ____]
print(result)`,
    solution_code: `result = [x**2 for x in range(1, 11) if x % 2 == 0]
print(result)`,
    hints: ['Square each number with x**2.', 'Filter even numbers with x % 2 == 0.'],
    test_cases: [
      { id: 1, description: 'Even squares from 1-10', setup_code: '', call_code: '', expected_output: '[4, 16, 36, 64, 100]' },
    ],
  },
  {
    id: 'code-sorting-003',
    type: 'coding',
    topic: 'Sorting',
    subtopic: 'lambda',
    difficulty: 'advanced',
    deck_source: 'Python Sorting, Tuples, and List Comprehensions.pptx',
    title: 'Sort Students by Grade',
    description: 'Write a function top_students(students) that takes a list of (name, grade) tuples and returns names sorted by grade, highest first.',
    exercise_type: 'write_from_scratch',
    starter_code: `def top_students(students):
    # your code here
    pass`,
    solution_code: `def top_students(students):
    return [name for name, grade in sorted(students, key=lambda s: s[1], reverse=True)]`,
    hints: ['Sort by grade (index 1) in descending order.', 'Use reverse=True for descending.', 'Extract just the names from the sorted result.'],
    test_cases: [
      { id: 1, description: 'Sort by grade desc', setup_code: '', call_code: 'print(top_students([("Alice", 85), ("Bob", 92), ("Carol", 78)]))', expected_output: "['Bob', 'Alice', 'Carol']" },
      { id: 2, description: 'Single student', setup_code: '', call_code: 'print(top_students([("Zoe", 100)]))', expected_output: "['Zoe']" },
    ],
  },
];
