import type { BankQuestion } from '../types';

export const stringsQuestions: BankQuestion[] = [
  // ─── Multiple Choice (10) ─────────────────────────────────────────────────
  // Migrated from baseline-test.ts (4)
  {
    id: 'mc-strings-001',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'len',
    difficulty: 'beginner',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What does len("hello") return?',
    options: ['4', '5', '6', '3'],
    correct_index: 1,
    explanation: 'len() counts characters. "hello" has 5 characters: h, e, l, l, o.',
  },
  {
    id: 'mc-strings-002',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'indexing',
    difficulty: 'beginner',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What is the output of "hello"[1]?',
    options: ['"h"', '"e"', '"l"', '"o"'],
    correct_index: 1,
    explanation: 'String indexing starts at 0. Index 1 refers to the second character, which is "e".',
  },
  {
    id: 'mc-strings-003',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'methods',
    difficulty: 'beginner',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'Which method converts a string to all uppercase letters?',
    options: ['.capitalize()', '.title()', '.upper()', '.lower()'],
    correct_index: 2,
    explanation: '.upper() converts all characters in the string to uppercase.',
  },
  {
    id: 'mc-strings-004',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'concatenation',
    difficulty: 'beginner',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What does "hello" + " world" produce?',
    options: ['"hello world"', '"helloworld"', 'Error', '"hello + world"'],
    correct_index: 0,
    explanation: 'The + operator concatenates (joins) two strings together, with the space included in the second string.',
  },
  // New MC questions (6)
  {
    id: 'mc-strings-005',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'slicing',
    difficulty: 'beginner',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What does "Python"[2:5] return?',
    options: ['"Pyt"', '"yth"', '"tho"', '"thon"'],
    correct_index: 2,
    explanation: 'Slicing s[2:5] returns characters at indices 2, 3, 4 — which are "t", "h", "o".',
  },
  {
    id: 'mc-strings-006',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'split/join',
    difficulty: 'intermediate',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What does "a,b,c".split(",") return?',
    options: ['"a b c"', '["a", "b", "c"]', '("a", "b", "c")', '["a,b,c"]'],
    correct_index: 1,
    explanation: '.split(",") splits the string at each comma and returns a list of substrings.',
  },
  {
    id: 'mc-strings-007',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'f-strings',
    difficulty: 'intermediate',
    deck_source: 'Understanding Python Strings - Part 2 (Session 4) (1).pptx',
    body: 'Given name = "Alice", what does f"Hello, {name}!" produce?',
    options: ['"Hello, {name}!"', '"Hello, Alice!"', 'Error', '"Hello, name!"'],
    correct_index: 1,
    explanation: 'f-strings evaluate expressions inside {} braces. {name} is replaced with the value of the variable name.',
  },
  {
    id: 'mc-strings-008',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'methods',
    difficulty: 'intermediate',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What does "hello world".replace("world", "Python") return?',
    options: ['"hello Python"', '"Python world"', '"hello world"', 'Error'],
    correct_index: 0,
    explanation: '.replace(old, new) returns a new string with all occurrences of old replaced by new.',
  },
  {
    id: 'mc-strings-009',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'slicing',
    difficulty: 'intermediate',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What does "abcdef"[-2:] return?',
    options: ['"ab"', '"ef"', '"de"', '"f"'],
    correct_index: 1,
    explanation: 'Negative indexing counts from the end. -2 is "e", and slicing to the end gives "ef".',
  },
  {
    id: 'mc-strings-010',
    type: 'multiple_choice',
    topic: 'Strings',
    subtopic: 'immutability',
    difficulty: 'advanced',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What happens when you run: s = "hello"; s[0] = "H"?',
    options: ['s becomes "Hello"', 'TypeError — strings are immutable', 's becomes "Hello" but a new object', 'IndexError'],
    correct_index: 1,
    explanation: 'Strings in Python are immutable. You cannot change individual characters. Use s = "H" + s[1:] instead.',
  },

  // ─── Open Answer (5) ──────────────────────────────────────────────────────
  {
    id: 'oa-strings-001',
    type: 'open_answer',
    topic: 'Strings',
    subtopic: 'slicing',
    difficulty: 'beginner',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What Python slice expression reverses a string? (e.g., turns "hello" into "olleh")',
    acceptable_answers: ['s[::-1]', '[::-1]', 'string[::-1]'],
    explanation: 'The slice [::-1] steps backward through the entire string, effectively reversing it.',
  },
  {
    id: 'oa-strings-002',
    type: 'open_answer',
    topic: 'Strings',
    subtopic: 'methods',
    difficulty: 'beginner',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What string method would you use to remove leading and trailing whitespace from a string?',
    acceptable_answers: ['.strip()', 'strip()', 'strip'],
    explanation: '.strip() removes leading and trailing whitespace characters from a string.',
  },
  {
    id: 'oa-strings-003',
    type: 'open_answer',
    topic: 'Strings',
    subtopic: 'split/join',
    difficulty: 'intermediate',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What is the output of " ".join(["Hello", "World"])?',
    acceptable_answers: ['Hello World', '"Hello World"'],
    explanation: '.join() concatenates list elements using the string as a separator. " ".join(["Hello", "World"]) produces "Hello World".',
  },
  {
    id: 'oa-strings-004',
    type: 'open_answer',
    topic: 'Strings',
    subtopic: 'f-strings',
    difficulty: 'intermediate',
    deck_source: 'Understanding Python Strings - Part 2 (Session 4) (1).pptx',
    body: 'Given x = 3.14159, write an f-string expression that formats x to 2 decimal places.',
    acceptable_answers: ['f"{x:.2f}"', "f'{x:.2f}'", '{x:.2f}'],
    explanation: 'f"{x:.2f}" uses the format specifier .2f to display a float with 2 decimal places.',
    grading_hint: 'Accept any f-string using :.2f format specifier',
  },
  {
    id: 'oa-strings-005',
    type: 'open_answer',
    topic: 'Strings',
    subtopic: 'methods',
    difficulty: 'advanced',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    body: 'What does "hello".find("ll") return?',
    acceptable_answers: ['2'],
    explanation: '.find() returns the index of the first occurrence of the substring. "ll" starts at index 2.',
  },

  // ─── Coding (5) ───────────────────────────────────────────────────────────
  // Migrated from practice-exercises.ts
  {
    id: 'code-strings-001',
    type: 'coding',
    topic: 'Strings',
    subtopic: 'slicing',
    difficulty: 'beginner',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    title: 'String Reversal',
    description: 'Fill in the blank to complete the function that reverses a string using Python slice notation.',
    exercise_type: 'fill_blank',
    starter_code: `def reverse_string(s):
    return s[____]`,
    solution_code: `def reverse_string(s):
    return s[::-1]`,
    hints: ["Python slices work like s[start:stop:step]. A step of -1 means 'go backwards'. Omitting start and stop uses the full string — so s[::-1] reverses it."],
    test_cases: [
      { id: 1, description: "'hello' → 'olleh'", setup_code: '', call_code: 'print(reverse_string("hello"))', expected_output: 'olleh' },
      { id: 2, description: "'Python' → 'nohtyP'", setup_code: '', call_code: 'print(reverse_string("Python"))', expected_output: 'nohtyP' },
      { id: 3, description: "Empty string stays empty", setup_code: '', call_code: 'print(reverse_string(""))', expected_output: '' },
    ],
  },
  {
    id: 'code-strings-002',
    type: 'coding',
    topic: 'Strings',
    subtopic: 'methods',
    difficulty: 'beginner',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    title: 'Count Vowels',
    description: 'Write a function count_vowels(s) that returns the number of vowels (a, e, i, o, u — case-insensitive) in the string s.',
    exercise_type: 'write_from_scratch',
    starter_code: `def count_vowels(s):
    # your code here
    pass`,
    solution_code: `def count_vowels(s):
    return sum(1 for c in s.lower() if c in 'aeiou')`,
    hints: ["Convert to lowercase first with .lower().", "Count characters that appear in the string 'aeiou'.", "A for loop or sum() with a generator expression both work."],
    test_cases: [
      { id: 1, description: "'hello' has 2 vowels", setup_code: '', call_code: 'print(count_vowels("hello"))', expected_output: '2' },
      { id: 2, description: "'Python' has 1 vowel", setup_code: '', call_code: 'print(count_vowels("Python"))', expected_output: '1' },
      { id: 3, description: "'aeiou' has 5 vowels", setup_code: '', call_code: 'print(count_vowels("aeiou"))', expected_output: '5' },
      { id: 4, description: 'Empty string → 0', setup_code: '', call_code: 'print(count_vowels(""))', expected_output: '0' },
    ],
  },
  {
    id: 'code-strings-003',
    type: 'coding',
    topic: 'Strings',
    subtopic: 'split/join',
    difficulty: 'intermediate',
    deck_source: 'Understanding Python Strings - Part 1 (Session 3) (1).pptx',
    title: 'Title Case Converter',
    description: 'Write a function title_case(s) that capitalizes the first letter of each word in a string. Do NOT use the built-in .title() method.',
    exercise_type: 'write_from_scratch',
    starter_code: `def title_case(s):
    # your code here
    pass`,
    solution_code: `def title_case(s):
    return ' '.join(word[0].upper() + word[1:] if word else '' for word in s.split(' '))`,
    hints: ['Split the string into words.', 'Capitalize the first character of each word using [0].upper() + [1:].', 'Join them back with spaces.'],
    test_cases: [
      { id: 1, description: "'hello world' → 'Hello World'", setup_code: '', call_code: 'print(title_case("hello world"))', expected_output: 'Hello World' },
      { id: 2, description: "'python is fun' → 'Python Is Fun'", setup_code: '', call_code: 'print(title_case("python is fun"))', expected_output: 'Python Is Fun' },
      { id: 3, description: "Single word", setup_code: '', call_code: 'print(title_case("hello"))', expected_output: 'Hello' },
    ],
  },
  {
    id: 'code-strings-004',
    type: 'coding',
    topic: 'Strings',
    subtopic: 'methods',
    difficulty: 'intermediate',
    deck_source: 'Understanding Python Strings - Part 2 (Session 4) (1).pptx',
    title: 'Palindrome Checker',
    description: 'Write a function is_palindrome(s) that returns True if the string reads the same forwards and backwards (case-insensitive, ignoring spaces).',
    exercise_type: 'write_from_scratch',
    starter_code: `def is_palindrome(s):
    # your code here
    pass`,
    solution_code: `def is_palindrome(s):
    cleaned = s.lower().replace(' ', '')
    return cleaned == cleaned[::-1]`,
    hints: ['Convert to lowercase and remove spaces first.', 'Compare the cleaned string to its reverse.'],
    test_cases: [
      { id: 1, description: "'racecar' is a palindrome", setup_code: '', call_code: 'print(is_palindrome("racecar"))', expected_output: 'True' },
      { id: 2, description: "'hello' is not", setup_code: '', call_code: 'print(is_palindrome("hello"))', expected_output: 'False' },
      { id: 3, description: "'A man a plan a canal Panama' (spaces ignored)", setup_code: '', call_code: 'print(is_palindrome("A man a plan a canal Panama"))', expected_output: 'False' },
      { id: 4, description: "'Race Car' case-insensitive", setup_code: '', call_code: 'print(is_palindrome("Race caR"))', expected_output: 'True' },
    ],
  },
  {
    id: 'code-strings-005',
    type: 'coding',
    topic: 'Strings',
    subtopic: 'f-strings',
    difficulty: 'advanced',
    deck_source: 'Understanding Python Strings - Part 2 (Session 4) (1).pptx',
    title: 'String Formatter',
    description: 'Fix the bug in this function that should format a person\'s info using f-strings.',
    exercise_type: 'fix_bug',
    starter_code: `def format_info(name, age, city):
    return f"{name} is {age} years old and lives in {City}."

print(format_info("Alice", 30, "NYC"))`,
    solution_code: `def format_info(name, age, city):
    return f"{name} is {age} years old and lives in {city}."

print(format_info("Alice", 30, "NYC"))`,
    hints: ['Check the variable names carefully — Python is case-sensitive.'],
    test_cases: [
      { id: 1, description: 'Correct output', setup_code: '', call_code: '', expected_output: 'Alice is 30 years old and lives in NYC.' },
    ],
  },
];
